[pytest]

addopts = -s -v --alluredir=./allure-results

reruns = 2
reruns_delay = 1

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: смоук тесты
    regression: регрессионные тесты
    authorization: тесты авторизации
